server:
  port: 2888

spring:
  datasource:
    username: root
    password: Fe@123456
    url: jdbc:mysql://116.62.186.162:3306/ryan?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

  redis:
    host: 116.62.186.162
    port: 6379
    database: 0

  lettuce:
    pool:
      # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
      max-wait: 60s
      # 连接池中的最大空闲连接 默认 8
      max-idle: 10
      # 连接池中的最小空闲连接 默认 0
      min-idle: 10
      # 连接池最大连接数（使用负值表示没有限制） 默认 8
      max-activ: 8




mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: org.example.entities

#showSql
logging:
  level:
    com:
      example:
        mapper : debug


